title = "o koda do irmão urso"
baseURL = "https://kodagabriel.github.io/"
languageCode = "pt"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "pt-br"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Escrevo por aí muita coisa."
  facebook = "https://facebook.com/ostrasvolateis"
  twitter = "https://twitter.com/ehkoda"
  instagram = "https://instagram.com/ehkoda"
  youtube = ""
  github = "https://github.com/kodagabriel"
  gitlab = ""
  linkedin = "https://linkedin.com/in/koda-gabriel/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/header2.jpg"
  recent_posts_number = 5
  show_reading_time = true
  disqusShortname = "kodagabriel"
  toc = true